services:
  - type: web
    name: pdf-converter
    env: ruby
    buildCommand: |
      # Установка wkhtmltopdf
      apt-get update -y
      apt-get install -y wkhtmltopdf xvfb
      bundle install
    startCommand: bundle exec rackup -p $PORT
    envVars:
      - key: RACK_ENV
        value: production 